### ISSUE TITLE
[UI] Add toasts for actions such as saving, loading, exporting, importing

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#109]
Which needs a dedicated place in the html, just like the Modals do.

I suggest an `atom` that holds the toasts-state and then do this:
https://react-bootstrap.netlify.app/docs/components/toasts/#stacking

Maybe also use it for warnings?

This proposal gets rid of the "out of place" message that we currently have.

**Comment by TheRedDaemon** [comment]
The State Buttons were updated with #128.  
I also saw that you removed the warning structures for these texts from the HTML (at least, I did not find them).  

So I guess the main thing left to do is styling and we have no design for them at the moment. But the functionality is implemented.
Should this issue be closed?

**Comment by gynt** [comment]
Not sure what you mean with warning structure.

**Comment by TheRedDaemon** [comment]
The divs to display the warning texts placed under the extension choosers or the config editor? At least, I was unable to find them the last time I looked, so I assumed you also removed them.

**Comment by gynt** [comment]
ah those! yea those are gone because they became toasts.
