### ISSUE TITLE
Add <base> to prevent links from changing the browser location

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#132]
Using https://www.npmjs.com/package/react-helmet?

https://github.com/tauri-apps/tauri/commit/757e959eb276ed535cfddb0dea8897c56441c644

**Comment by TheRedDaemon** [comment]
Can you elaborate? What is the issue, how does this effect us?

**Comment by gynt** [comment]
e.g. the credits window has hyperlinks in them, which is currently working correctly, e.g. opening a new tab in the default browser. It is working fine because I included a rehype-external-links plugin (to inject target=_blank when markdown is converted to html). Apparently, this base thing can do this trick without the rehype-external-links plugin. Since the base thing is more generic, and should be applied in most cases, unless I am overlooking a scenario in which we want to have the hyperlink behavior, I think it is preferred.

**Comment by TheRedDaemon** [comment]
We talked about this and you switched to an approach with a custom link renderer. Can this be closed?

**Comment by gynt** [comment]
Solved in d0283f3ba13ca51220e1ee2383b00e9ab09a2b11
