### ISSUE TITLE
Refactor svg images into files instead of inline

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#141]
Temporary fix for this issue https://github.com/vitejs/vite/issues/15453 was to do inline svg's.

We should create file svgs and import those when this issue has been fixed.

**Comment by TheRedDaemon** [comment]
Changed the temporary fix to also use inline svgs, but as source for the other svg and loaded from the files based on an idea from the Vite issue thread.  
Issue still applies, though.
