### ISSUE TITLE
Improve toasts by making React key fields unique

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#149]
Errors can occur and autohide can stop functioning if key's are not unique. Currently they are the JSON value of the title and body of the toast, but this is not guaranteed to be unique before one toast is autohidden again.

**Comment by TheRedDaemon** [comment]
Started work on the toasts. Also adding config options to address #148

**Comment by TheRedDaemon** [comment]
Should also be solved by #150
