### ISSUE TITLE
[INSTALLER] Customize NSIS Installer

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UCP3-GUI#152]
Tauri already offers some ways to customize the installer, like including a license: https://tauri.app/v1/guides/building/windows/#customizing-the-nsis-installer-template

This should be done (at least in the future).

**Comment by TheRedDaemon** [comment]
Hi @Monsterfisch, can you help out with the image data for the installer?

Collection of required picture data:

| Name | File Type | Description |
| - | - | - |
| headerImage  | .bmp  | The path to a bitmap file to display on the header of installers pages. The recommended dimensions are 150px x 57px.  |
| sidebarImage  | .bmp  | The path to a bitmap file for the Welcome page and the Finish page. The recommended dimensions are 164px x 314px.  |
| installerIcon  | .ico  | The path to an icon file used as the installer icon.  |

It would be best to stick to the recommended sizes. It provides a nice orientation.

The `sidebarImage` should be easily visible here on the left (and the icon in the window header):

![grafik](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/66257843/804894a8-e91a-442f-96f8-8cfbdfd867ef)

I am not 100% sure regarding the `headerImage` (since I find no example online that says "That is it!"), but I think it is the image in the upper right in the header:

![grafik](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/66257843/4a83c352-fd4b-47ce-a81c-e9bb1af3f8c5)

**Comment by Monsterfisch** [comment]
[installer.zip](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/files/14419273/installer.zip)
lemme know if you need anything else =)

**Comment by TheRedDaemon** [comment]
Awesome, thanks for the quick work.

@Monsterfisch 
We are close, but the installer tricked us: 🙃 
![grafik](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/66257843/e70f0389-698b-46e5-81c4-78aaed9d23f4)

Otherwise it looks good:
![grafik](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/66257843/3f9843f5-233e-4651-964c-4b94a255c7f6)

Can you change the `headerImage` to fit into its actual spot?

**Comment by Monsterfisch** [comment]
![headerImage](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/24592166/bc8e0b80-f2a3-45ae-a176-96c289834b31)
this should be left/right resilient ;)

**Comment by TheRedDaemon** [comment]
Sieht gut aus. 👍 

![grafik](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/66257843/e18f5ad3-1505-4540-a2c0-4650a2d3f6ae)

Ich geb die MR nun frei. Besten Dank.
