### ISSUE TITLE
[INSTALLER] Installer asks for admin access

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#158]
The new installer/updater (some settings where changed somewhere?) requires elevated privileges.
The installer/updater before that didn't require this, which I prefer a lot!

The new install location is Program Files/UCP3-GUI
The old install locations was: AppData/Local/UCP3-GUI

Can the install location be set to AppData again?

@TheRedDaemon

**Comment by gynt** [comment]
Ah I guess this is it: https://tauri.app/v1/api/config/#nsisinstallermode

**Comment by gynt** [comment]
5beccca

**Comment by gynt** [comment]
5beccca

**Comment by TheRedDaemon** [comment]
Well, I do not care about admin rights being needed, hate programms that want to install into my app data, but I am fine providing the option. I think that should at least explain why I set the setting. 🙂 That being said, the last word is on you and you found the option anyway. 😁

**Comment by gynt** [comment]
I am giving preference to no-admin privileges required because my AV already flags every new setup/update of the GUI. So I expect people who are new to become scared if admin priv is asked for :)

**Comment by TheRedDaemon** [comment]
If this is changed, then I think you can close this.

**Comment by gynt** [comment]
yea I needed a few version updates to make sure it all works :) That is why it is still open. v0.0.23 should give me closure about this.

**Comment by TheRedDaemon** [comment]
@gynt we are on 0.0.25. Did you find closure? 😉

**Comment by gynt** [comment]
Yes it even works on my work laptop which has very restrictive policies!
