### ISSUE TITLE
[CSP] Discord banner not allowed

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UCP3-GUI#160]
Currently, the CSP does not allow the Discord banner:
![grafik](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/66257843/20c11c06-5535-4f38-8f50-d4bce5803527)
*Error*:
`Refused to load the image 'https://discordapp.com/api/guilds/426318193603117057/widget.png?style=shield' because it violates the following Content Security Policy directive: "img-src 'self' data: asset: https://asset.localhost".`

Now, the CSP is a safety measure. The question now is: Do we allow more picture sources? Or only the banner? Or not at all?

**Comment by gynt** [comment]
I like the banner, but we can add that somewhere else in the GUI with a special button taking you to the GitHub and a button for taking you to the Discord.
Would you like to include images that can't be converted to a data image in base64?

**Comment by TheRedDaemon** [comment]
Sorry, I can not understand your question. It is fine to include images in the repo, or what do you mean?

**Comment by gynt** [comment]
Well if CSP prevents us from displaying the image via a url, why not include the Discord banner directly with a base64 data image?

**Comment by TheRedDaemon** [comment]
That is possible.

**Comment by gynt** [comment]
Or this:
https://github.com/tauri-apps/tauri-docs/issues/26#issuecomment-1908907632

**Comment by TheRedDaemon** [comment]
Solved with #176
