### ISSUE TITLE
[INSTALLER/UPDATER] Notification window does not fit message.

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UCP3-GUI#161]
The update notification does not fit the info window:
![grafik](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/assets/66257843/df01a95f-70b3-4668-8c2b-ab318a7981ae)
The link to the changelog does not fit.

It would be nice if this could be fixed.  
That being said, maybe another approach could also be used, since the text is not copyable (at least when I tried).

**Comment by gynt** [comment]
Yes it really annoys me it wants Release Notes in that dialog box at all... The link looks nice on GitHub, but not in this dialog indeed.

tauri-apps/tauri-action
