### ISSUE TITLE
[LAUNCH] Release Build: Launching a game creates a visible console

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UCP3-GUI#165]
I did not notice this effect when I used the dev build.

This should be compared with the dev build and at best fixed.
It is not a functional issue, but a bit ugly. Maybe the command can be executed without the visible console.

**Comment by TheRedDaemon** [comment]
[This](https://stackoverflow.com/a/75292572) might be the quickest solution (for windows).
Saw also [this answer](https://stackoverflow.com/a/75292572) in another question that directly used a DETACHED_PROCESS flag, but no idea if this means that we at least get the result of the launch function.

The first one might pontially the solution without unknown side effects.

**Comment by gynt** [comment]
You pasted the same URL twice :) But I trust you on this one!

**Comment by TheRedDaemon** [comment]
Fixed URL.

**Comment by TheRedDaemon** [comment]
@gynt Is this gone? I can not remember it appearing again. If you also do not encouter it with the release version anymore, then this can be closed, I guess.
