### ISSUE TITLE
[LANGUAGE] Make language files accessible to make translation contribution easier

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#169]
Requires this: https://tauri.app/v1/guides/building/resources/
How would this work with i18next?

**Comment by gynt** [comment]
Also needs a file based logic for detecting which languages we support I guess so people can add translations themselves and see how it fits. Not truly necessary perhaps because they can mod the English language file in place piece by piece.

**Comment by TheRedDaemon** [comment]
I mean, the supported languages are already handled via a file. It would also just need to be exposed, or not?
