### ISSUE TITLE
[LOCALIZATION] Resource method for localization files prevents runtime change

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UCP3-GUI#191]
Previously, the localization files were loaded as asset, therefore Vite took care and at least reloaded them on restart.  
Now, as a resource file, the files are copied once even during the dev setup and are then placed in the target directory (in case of dev debug).

This means changes in the resources folder have then no effect. To change the data on demand, the files in the target dir would need to get changed and succesful changes then copied. However, in case of the release app, this is the only place given and the translators oftern worked with the text files only it seems. So maybe this is not a problem?

What do you think, @gynt? To be fair, I tested some stuff that did not work, but if it is realy needed, I could test some more (but it does not look good).

**Comment by gynt** [comment]
Just to get the problem straight, you mean that in developer mode (npm run dev) changes to the locale files don't cause an automatic refresh of the app, right? I noticed it too but I don't think it is a big issue, just slightly annoying.

Or is there an issue in production version of the app?

**Comment by TheRedDaemon** [comment]
There should be no issues with this in the production version. In fact, modifying the files in the install directory will have the effect the dev version had earlier (reload on app reload). I guess this can be closed then. It is just something to keep in mind during development.
