### ISSUE TITLE
[QOL] Add check if C++ redistributable is installed

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#223]
As I experienced yesterday, users can be faced with a crash upon game start if UCP is framework is activated but https://aka.ms/vs/17/release/vc_redist.x86.exe is not installed. I found a source on how to check if this is installed: https://stackoverflow.com/questions/46178559/how-to-detect-if-visual-c-2017-redistributable-is-installed

Rust needs to check this: `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x86`
and if a 32-bit OS this `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x86` to see if a key named "Installed" has `REG_DWORD` data `1`.

Preferably this is checked before the framework is installed using the install framework button.

Or even better, the GUI installer should include this requirement... but coding that might be a few magnitudes more difficult...

**Comment by TheRedDaemon** [comment]
Seems I kinda showed my lack of knowledge. Would have never guessed that the MSVC standard library is actually a dynamically linked dependency. The lack of error is confussing, though. @gynt Can you check if wuch errors are devoured by the way the DLLs are loaded? Including the installer depends on where you want it. As part of the framework installation would already be a lot of work, but as part of the GUI installer would be a LOT of work...

**Comment by gynt** [comment]
I wouldn't recommend including the installer, just a Modal box if the GUI is running on Windows telling the user they need to install it and then provide a link to do it in that modal box. That would be enough I think.

The game simply crashes without producing any logs whatsoever, so I can't really test out the inner workings of the error. I actually hypothesize that they might have only installed x64 and not the x86 one?

**Comment by TheRedDaemon** [comment]
I would still be curious... the liberary that handles the in-memory loading also needs to resolve the dependencies, or not?

A lot of games, etc. throw an error box if a dll is missing. I am just wondering why this is not the case here.
Are there errors if another dll is missing?

**Comment by gynt** [comment]
Maybe this can be done as an alternative solution: https://stackoverflow.com/a/62092186/26134966

Yes I am also in the dark about why there is no pop up. The only thing I can imagine is a x86 x64 thing going on, or the custom dll loading, but I can't imagine that is it, because the main ucp dll already needs the runtime... What I think actually happened is that I included the `<random>` library in the ucp dll which caused a dependency on a newer version of the C++ runtime that many don't have installed already...

**Comment by gynt** [comment]
Resolved in afa8f9628ad8c64ec4b68a923610c0110b65f4cb
