### ISSUE TITLE
Bug: having an unsupported extension (e.g. framework version demand too high) in the config crashes the GUI

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#228]

**Comment by Krarilotus** [comment]
Is this still an issue?

**Comment by gynt** [comment]
Yes I think so, reproducability instructions:
1. modify one definition.yml to depend on frontend version higher than you have installed. 
2. Refresh the GUI and see it break

The solution is to have a proper try catch somewhere.
