### ISSUE TITLE
Bug: activating an older version of a module doesn't always work and breaks the GUI

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#229]
Basically there is an error, but the configuration is still half configured somehow.

Reproduction steps:
- Copy a module
- Give it an older version number in the zip name and in the description.yml inside the zip
- Observe in the GUI that two versions are available (use the dropdown)
- Try to select the lower version and add it to the activated extensions
- Crash

**Comment by Krarilotus** [comment]
@gynt any way i can test this and narrow it down for you guys, or is it clear why that happens?

**Comment by gynt** [comment]
> @gynt any way i can test this and narrow it down for you guys, or is it clear why that happens?

I added reproduction steps
