### ISSUE TITLE
[QOL]: Make customisations tab visible by default

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#231]
Make the customisations tab by default visible.

Pros:
- Clear what is possible

Cons:
- Clutter for users who only activate content from the store

https://github.com/UnofficialCrusaderPatch/UCP3-GUI/issues/220

**Comment by Krarilotus** [comment]
Can we maybe have the 'Creator Version' of the GUI automatically have this tab?
I know, this might be a new issue but these things also have come up when dealing with modding users of the UCP:
- people tend to click on 'customizations' twice to reach teh customizations tab, as it switches them over to the tab the first time, so they think that is the way they access it, making it hard to teaching them that there is a tab. 
-> Maybe we should rename the toggle once activated? @Monsterfisch maybe we can have a 'pressed button' grafics, so it is like a permanently pressed button, that is obviously 'active'
- people tend to want to modify plugins in the content tab, but are not able to, unless they first switch tab to customizations then click the palette icon, and they don't even know this could be a thing...
-> 2 suggestions: 
  - make also sure to see that this is a toggle button, and make more clear what its function is: Activating the plugin creation and modification @Monsterfisch  might come up with a new art design or an updated version of this button?
  - make this button available in the content tab as well, sharing its properties with that one in the customizations tab
