### ISSUE TITLE
[QOL] GUI-status save between sessions

### ISSUE THREAD

**Issue by Krarilotus** [UnofficialCrusaderPatch/UCP3-GUI#241]
When you open the GUI up, you are prompted to select an installation path.
- There is also the ability to change the installation path and use a different one
It would be nice, if we could keep the installation path that was last selected selected upon restarting the GUI, as it is often required to restart the GUI for using the features of the GUI currently

Further down the line, it might make sense to have the GUI reload the actions that it usually needs to be restarted for instead, but regardless i think the installation path should be saved whenever it is switched in some gui-intermediate config

While we are at it, as some thigns are only viable for the non-dev version with launch time parameters, like the opening of multiple instances of Stronghold Crusader, it would be nice if these could also be saved between sessions. So upon launching the game with certain parameters, it would be nice if that was added to the GUI config as well, so that users wanting to use those wouldn't for example have to retype  --ucp-no-security into their parameters everytime they restarted their UCP3 GUI.

**Comment by gynt** [comment]
Resolved in 7ddb45c845e9ecb5a7314a182d249d58825bd5c5
