### ISSUE TITLE
[QoL] move caret to the left side for easier identifiability ucp2 style

### ISSUE THREAD

**Issue by Krarilotus** [UnofficialCrusaderPatch/UCP3-GUI#242]
elapseable options are great, but not if you can't really use the feature without leaving your safe space and its hard to even know which caret belongs to which feature....
-> hence we should probably move the caret to the left side :)
Like this: 
![image](https://github.com/user-attachments/assets/93bfea56-3772-4edb-bf3f-522831598f9e)

**Comment by Krarilotus** [comment]
nvm gynt was faster o.O

**Comment by Krarilotus** [comment]
#240 fixes this
perfect :)

**Comment by gynt** [comment]
Addressed in 4e5f395138e10924818a9b89d569a2abc927940b
