### ISSUE TITLE
Make Reload button invalidate the query cache for update checks and store files

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#297]
Makes it easier to recover from invalid installation state.

The issue being that the install button is greyed out even if the installation had a failure halfway through.

**Comment by Krarilotus** [comment]
Question: Isn't reload equivalent to restarting the GUI? 
-> If thats so, i woudl expect behaviour like this:
1. reload basically just shuts down everything
2. loads all config from drive

If caches are involved, i would expect:
1. Whenever something that changes files on drive, it also gets saved to cache
2. Extra cache changes get tracked, reload resets cache to state for everything that's also stored on drive

**Comment by gynt** [comment]
> Question: Isn't reload equivalent to restarting the GUI?

No not anymore since 1.0.7+
